- name: install nginx
  apt:
    name:
      - "{{ nginx_package }}"
      - python3-passlib
    state: present


- name: setup /etc/nginx/nginx.conf
  template:
    src: "templates/etc/nginx/nginx.conf.j2"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - verify nginx config
    - restart nginx


- name: create directory for vhost inlcudes
  file:
    state: directory
    path: /etc/nginx/includes
    owner: root
    group: root
    mode: 0750

- name: setup vhost includes
  template:
    src: "templates/etc/nginx/includes/{{ nginx_include_item }}.conf.j2"
    dest: "/etc/nginx/includes/{{ nginx_include_item }}.conf"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ nginx_includes }}"
  loop_control:
    loop_var: nginx_include_item


- name: create htpasswd users
  htpasswd:
    path: "{{ nginx_htpasswd_file }}"
    name: "{{ htpasswd_present_item.name }}"
    password: "{{ htpasswd_present_item.pass }}"
    owner: root
    group: www-data
    mode: 0640
  with_items: "{{ nginx_htpasswd_present }}"
  loop_control:
    loop_var: htpasswd_present_item

- name: remove htpasswd users
  htpasswd:
    path: "{{ nginx_htpasswd_file }}"
    name: "{{ htpasswd_absent_item }}"
    state: absent
  with_items: "{{ nginx_htpasswd_absent }}"
  loop_control:
    loop_var: htpasswd_absent_item

- name: remove nginx vhost created by nginx package
  file:
    path: "{{ nginx_pkg_maintainer_default_vhost }}"
    state: absent
  with_items:
    - "/etc/nginx/sites-available/default"
    - "/etc/nginx/sites-enabled/default"
  loop_control:
    loop_var: nginx_pkg_maintainer_default_vhost


- name: remove nginx_vhosts_absent from /etc/nginx/sites-enabled
  file:
    path: "/etc/nginx/sites-enabled/{{ nginx_vhost_absent }}.conf"
    state: absent
  with_items: "{{ nginx_vhosts_absent }}"
  loop_control:
    loop_var: nginx_vhost_absent
  notify:
    - verify nginx config
    - reload nginx

- name: remove nginx_vhosts_absent from /etc/nginx/sites-available
  file:
    path: "/etc/nginx/sites-available/{{ nginx_vhost_absent }}.conf"
    state: absent
  with_items: "{{ nginx_vhosts_absent }}"
  loop_control:
    loop_var: nginx_vhost_absent
  notify:
    - verify nginx config
    - reload nginx


- name: create nginx vhosts
  template:
    src: "{{ nginx_vhost_present['template'] }}"
    dest: "/etc/nginx/sites-available/{{ nginx_vhost_present['name'] }}.conf"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ nginx_vhosts_present }}"
  loop_control:
    loop_var: nginx_vhost_present
  notify:
    - verify nginx config
    - reload nginx

- name: enable nginx vhosts
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ nginx_vhost_present['name'] }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_vhost_present['name'] }}.conf"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ nginx_vhosts_present }}"
  loop_control:
    loop_var: nginx_vhost_present
  notify:
    - verify nginx config
    - reload nginx


- name: enable nginx modules
  file:
    state: link
    src: "/usr/share/nginx/modules-available/{{ nginx_module_enabled }}"
    dest: "/etc/nginx/modules-enabled/{{ nginx_module_enabled }}"  
  with_items: "{{ nginx_modules_enabled }}"
  loop_control:
    loop_var: nginx_module_enabled
  notify:
    - verify nginx config
    - restart nginx

- name: disable nginx modules
  file:
    state: absent
    path: "/etc/nginx/modules-enabled/{{ nginx_module_disabled }}"
  with_items: "{{ nginx_modules_disabled }}"
  loop_control:
    loop_var: nginx_module_disabled
  notify:
    - verify nginx config
    - restart nginx
