- name: verify nginx config
  command: nginx -t

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
    enabled: True

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: True
