---
- name: verify Nginx config
  become: yes
  command: nginx -t

- name: reload Nginx
  service:
    name: nginx
    state: reloaded

- name: restart Nginx
  service:
    name: nginx
    state: restarted
