- name: deploy nginx main configuration file
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: ensure vhost absence
  when: nginx_vhost_absent
  file:
    path: /etc/nginx/sites-enabled/{{ nginx_server_name }}.conf
    state: absent
  with_items: '{{ nginx_vhost_absent }}'
