- name: deploy nginx main configuration file
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: ensure vhost absence
  file:
    path: /etc/nginx/sites-enabled/{{ absent_vhost_item }}
    state: absent
  with_items: '{{ nginx_vhost_absent }}'
  loop_control:
    loop_var: absent_vhost_item
  notify: reload nginx
